export type OperationTool =
  | "select"
  | "lasso"
  | "height"
  | "distance"
  | "extend"
  | "angle"
  | "move"
  | "scale"
  | "rotate"
  | "rotateAxis"
  | "moveFace"
  | "bend"
  | "moveQuestion"
  | "fillet"
  | "booleanUnion"
  | "booleanSubtract"
  | "booleanIntersect";